#!/usr/bin/env python3

import requests
import json

def get_public_ip():
    response = requests.get("http://whatismyip.akamai.com/")
    print(f"Your public IP Address is {response.text}")
    return response.text

def get_ip_geoloc(ip):
    session = requests.Session()
    uri = f"https://tools.keycdn.com/geo.json?host={ip}"
    session.headers.update({ 'User-Agent': 'keycdn-tools:https://me.me' })
    response = session.get(uri)
    json_response = json.loads(response.text)
    country = json_response["data"]["geo"]["country_name"]
    city = json_response["data"]["geo"]["city"]
    region = json_response["data"]["geo"]["region_name"]
    lat = json_response["data"]["geo"]["latitude"]
    long = json_response["data"]["geo"]["longitude"]
    print(f"\nCountry: {country}\nCity: {city}\nRegion: {region}\nCoordinates: {lat},{long}")
    
ipaddr = get_public_ip()
get_ip_geoloc(ipaddr)